$VAR1 = {
          '*(intptr+1) = "ofd"' => '',
          '*(intptr+4) = "ofd"' => 'this.HEAP32[intptr+4*4>>2] = ofd;',
          '*intptr = "avail"' => 'this.HEAP32[intptr>>2] = avail;',
          '*intptr = "ifd"' => '',
          '*intptr = "ofd"' => '',
          '*intptr = 0' => 'this.HEAP32[intptr>>2] = 0;',
          'AT_EMPTY_PATH' => '4096',
          'AT_FDCWD' => '-100',
          'AT_FDROOTD' => '-101',
          'EBADF' => '9',
          'EINVAL' => '22',
          'EIO' => '5',
          'ENOENT' => '2',
          'ENOMEM' => '12',
          'FIONREAD' => '21531',
          'POLLIN' => '1',
          'SEEK_CUR' => '1',
          'SEEK_END' => '2',
          'SEEK_SET' => '0',
          'S_IFDIR + 0777' => '16895',
          '__S_IFCHR + 0666' => '8630',
          'direntp+&dirent::d_name' => 'direntp+19',
          'direntp[&dirent::d_ino] = "0"' => 'this.HEAP32[direntp>>2] = 0;',
          'direntp[&dirent::d_off] = "0"' => 'this.HEAP32[direntp+8>>2] = 0;',
          'direntp[&dirent::d_reclen] = 9' => 'this.HEAP16[direntp+16>>1] = 9;',
          'fdsptr[i+&pollfd::events]' => 'this.HEAP16[fdsptr+i*8+4>>1]',
          'fdsptr[i+&pollfd::fd]' => 'this.HEAP32[fdsptr+i*8>>2]',
          'fdsptr[i+&pollfd::revents]' => 'this.HEAP16[fdsptr+i*8+6>>1]',
          'fdsptr[i+&pollfd::revents] = 0' => 'this.HEAP16[fdsptr+i*8+6>>1] = 0;',
          'iov[i+&iovec::iov_base]' => 'this.HEAP32[iov+i*8>>2]',
          'iov[i+&iovec::iov_len]' => 'this.HEAP32[iov+i*8+4>>2]',
          'sizeof(struct stat)' => '176',
          'statbufptr[&stat::st_blksize] = "fd.size()"' => 'this.HEAP32[statbufptr+56>>2] = fd.size();',
          'statbufptr[&stat::st_blocks] = "1"' => 'this.HEAP32[statbufptr+64>>2] = 1;',
          'statbufptr[&stat::st_mode] = "fd.mode()"' => 'this.HEAP32[statbufptr+24>>2] = fd.mode();',
          'statbufptr[&stat::st_mode] = 0666' => 'this.HEAP32[statbufptr+24>>2] = 438;',
          'statbufptr[&stat::st_nlink] = 1LL' => 'this.HEAP32[statbufptr+16>>2] = 1; this.HEAP32[statbufptr+16+4>>2] = 0;',
          'statbufptr[&stat::st_size] = "fd.size()"' => 'this.HEAP32[statbufptr+48>>2] = fd.size();',
          'timespec[&timespec::tv_nsec] = "ns"' => 'this.HEAP32[timespec+8>>2] = ns;',
          'timespec[&timespec::tv_nsec] = 0' => 'this.HEAP32[timespec+8>>2] = 0; this.HEAP32[timespec+8+4>>2] = 0;',
          'timespec[&timespec::tv_sec] = "s"' => 'this.HEAP32[timespec>>2] = s;',
          'timespec[&timespec::tv_sec] = 0' => 'this.HEAP32[timespec>>2] = 0; this.HEAP32[timespec+4>>2] = 0;',
          'tp1' => '8192',
          'tp1[&threadpage::bottom_of_stack] = "module.bottom_of_stack"' => 'HEAP32[8192+24>>2] = module.bottom_of_stack;',
          'tp1[&threadpage::id] = "1"' => 'HEAP32[8192+16>>2] = 1;',
          'tp1[&threadpage::initsp] = "sp"' => 'HEAP32[8192+64>>2] = sp;',
          'tp1[&threadpage::next]' => 'HEAP32[8192>>2]',
          'tp1[&threadpage::pc] = "process.entry"' => 'HEAP32[8192+48>>2] = process.entry;',
          'tp1[&threadpage::prev]' => 'HEAP32[8192+8>>2]',
          'tp1[&threadpage::sp]' => 'HEAP32[8192+56>>2]',
          'tp1[&threadpage::sp] = "sp"' => 'HEAP32[8192+56>>2] = sp;',
          'tp1[&threadpage::top_of_stack] = "module.top_of_stack"' => 'HEAP32[8192+32>>2] = module.top_of_stack;',
          'tp[&threadpage::initsp]' => 'this.HEAP32[this.threadpage+64>>2]',
          'tp[&threadpage::pc]' => 'this.HEAP32[this.threadpage+48>>2]',
          'tp[&threadpage::sp]' => 'this.HEAP32[this.threadpage+56>>2]',
          'tp[&threadpage::stop_reason]' => 'this.HEAP32[this.threadpage+40>>2]',
          'tvptr[&timeval::tv_sec]' => 'this.HEAP32[tvptr>>2]',
          'tvptr[&timeval::tv_sec] = "s"' => 'this.HEAP32[tvptr>>2] = s;',
          'tvptr[&timeval::tv_usec]' => 'this.HEAP32[tvptr+8>>2]',
          'tvptr[&timeval::tv_usec] = "us"' => 'this.HEAP32[tvptr+8>>2] = us;',
          'zp[&zeropage::bottom_of_sbrk] = "module.start_of_sbrk"' => 'HEAP32[4096+24>>2] = module.start_of_sbrk;',
          'zp[&zeropage::thread_list]' => 'HEAP32[4096+16>>2]',
          'zp[&zeropage::top_of_memory]' => 'this.HEAP32[4096>>2]',
          'zp[&zeropage::top_of_memory] = "module.top_of_memory"' => 'HEAP32[4096>>2] = module.top_of_memory;',
          'zp[&zeropage::top_of_sbrk]' => 'this.HEAP32[4096+8>>2]',
          'zp[&zeropage::top_of_sbrk] = "module.start_of_sbrk"' => 'HEAP32[4096+8>>2] = module.start_of_sbrk;'
        };
