* Overview

This is a port of various GNU utilities to work with or on an "architecture" based on the asm.js subset of JavaScript; the compiler used is GCC, which means C and C++ programs (and, in theory, programs in other languages) can be compiled to JavaScript code that can then be run in a web browser or JavaScript shell.

It's quite slow, partly because of the design of the architecture.

It was originally based on Emscripten, but no Emscripten code remains at this point; instead, GCC and glibc are used.

* Pipeline
The stages of building a JavaScript program are as follows:
** GCC translates C/C++ code to "assembler" code
** GNU as translates "assembler" code into an ELF object file
** GNU ld links the ELF object files into an ELF executable
** GNU objcopy extracts the raw data file
** "hexify" turns the data file into a JSON array
** GNU objcopy adds this array to the ELF executable as a new section
** GNU ld creates a temporary ELF object with JavaScript support code and the ELF executable
** GNU ld turns this temporary ELF object file into JavaScript
* Repositories

** https://github.com/pipcet/binutils-gdb
https://github.com/pipcet/binutils-gdb/tree/asmjs
*** Build instructions
Assuming that $HOME/git/binutils-gdb is where you want your cloned git tree to end up, $HOME/build/binutils-gdb is where you want to build it, and $HOME/asmjs-virtual-asmjs is the prefix to be used for installing programs and libraries:

$ cd $HOME/git
$ git clone https://github.com/pipcet/binutils-gdb -b asmjs
$ (cd binutils/gas; aclocal-1.11; AUTOCONF=autoconf2.64 automake-1.11))
$ mkdir $HOME/build/binutils-gdb
$ cd $HOME/build/binutils-gdb
$ ~/git/binutils-gdb/configure --target=asmjs-virtual-asmjs --prefix=$HOME/asmjs-virtual-asmjs
$ make
$ make install

** https://github.com/pipcet/gcc
https://github.com/pipcet/gcc/tree/asmjs
*** Build instructions
GCC needs to be built twice (at present); once before glibc is built, then again after glibc is built.

**** Pre-glibc build
Assuming that $HOME/git/gcc is where you want your cloned git tree to end up, $HOME/build/gcc is where you want to build it, and $HOME/asmjs-virtual-asmjs is the prefix to be used for installing programs and libraries:

$ cd $HOME/git
$ git clone https://github.com/pipcet/gcc -b asmjs
$ mkdir $HOME/build/gcc
$ cd $HOME/build/gcc
$ ~/git/gcc/configure --target=asmjs-virtual-asmjs --disable-libatomic --disable-libgomp --disable-libquadmath --enable-explicit-exception-frame-registration --enable-languages=c --prefix=$HOME/asmjs-virtual-asmjs --disable-libssp
$ make
$ make install
