#!/usr/bin/perl
my $lastaddr = 0;
while (<>) {
    chomp;
    if (/(0x[0-9a-f]*)/) {
        my $addr = hex $1;

        if ($addr <= $lastaddr) {
            print "$_\n";
            $lastaddr += 0x1000;
        } elsif ($addr == $lastaddr + 0x1000 || $lastaddr == 0) {
            print "$_\n";
            $lastaddr = $addr;
        } else {
            print "$_\n";
            $lastaddr += 0x1000;
            redo;
        }
    }
}
