        .include "wasm32-macros.s"
        .globl f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
        defun f0 FiE
        i32.const 0
        return
        end
        endefun f0
        defun f1 FiiE
        get_local 0
        return
        end
        endefun f1
        defun f2 FiiiE
        get_local 0
        get_local 1
        i32.add
        return
        end
        endefun f2
        defun f3 FiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        return
        end
        endefun f3
        defun f4 FiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        return
        end
        endefun f4
        defun f5 FiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        return
        end
        endefun f5
        defun f6 FiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        return
        end
        endefun f6
        defun f7 FiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        return
        end
        endefun f7
        defun f8 FiiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        get_local 7
        i32.add
        return
        end
        endefun f8
        defun f9 FiiiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        get_local 7
        i32.add
        get_local 8
        i32.add
        return
        end
        endefun f9
        defun f10 FiiiiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        get_local 7
        i32.add
        get_local 8
        i32.add
        get_local 9
        i32.add
        return
        end
        endefun f10
        defun f11 FiiiiiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        get_local 7
        i32.add
        get_local 8
        i32.add
        get_local 9
        i32.add
        get_local 10
        i32.add
        return
        end
        endefun f11
        defun f12 FiiiiiiiiiiiiiE
        get_local 0
        get_local 1
        i32.add
        get_local 2
        i32.add
        get_local 3
        i32.add
        get_local 4
        i32.add
        get_local 5
        i32.add
        get_local 6
        i32.add
        get_local 7
        i32.add
        get_local 8
        i32.add
        get_local 9
        i32.add
        get_local 10
        i32.add
        get_local 11
        i32.add
        return
        end
        endefun f12
