#!/bin/bash
test -x $1 || (echo "argument $1 not present or not executable" > /dev/stderr; exit 1)
mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
echo ':wasm:M::\x00asm\x01\x00\x00\x00:\xff\xff\xff\xff\xff\xff\xff\xff:'"$1"':' > /proc/sys/fs/binfmt_misc/register
