#!/bin/bash
test -x $1 || (echo "argument $1 not present or not executable" > /dev/stderr; exit 1)
mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
echo ':wasm32:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x57\x41:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:'"$1"':' > /proc/sys/fs/binfmt_misc/register
